/*
 * GuiMain.java
 *
 * Created on Mar 4, 2012, 2:45:52 PM
 */

package voglet;

/**
 *
 * @author michael
 */
public class GuiMain extends javax.swing.JFrame {
    private boolean bExit;
    private VocabularySet set;
    private Entry actualEntry;
    /** Creates new form GuiMain */
    public GuiMain(VocabularySet set) {
        initComponents();
        this.set = set;
        this.setNewEntry();
	this.bExit = false;
    }

	public boolean isbExit() {
		return bExit;
	}

	public void setbExit(boolean bExit) {
		this.bExit = bExit;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblWord = new javax.swing.JLabel();
                tfTranslation = new javax.swing.JTextField();
                btnNext = new javax.swing.JButton();
                btnOk = new javax.swing.JButton();
                lblCorrectTranslation = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lblWord.setText("word");

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });

                btnOk.setText("Ok");
                btnOk.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnOkActionPerformed(evt);
                        }
                });

                lblCorrectTranslation.setText("jLabel2");

                jButton1.setText("jButton1");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCorrectTranslation)
                                        .addComponent(lblWord, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(tfTranslation, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addComponent(btnOk)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnNext)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addComponent(jButton1))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblWord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfTranslation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCorrectTranslation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNext)
                                        .addComponent(btnOk))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                lblWord.getAccessibleContext().setAccessibleName("lblWord");
                tfTranslation.getAccessibleContext().setAccessibleName("tfTranslation");

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void setNewEntry() {
        this.actualEntry = this.set.getRandomEntry();
        this.lblWord.setText( this.actualEntry.getWordByRandom() );
        this.lblCorrectTranslation.setVisible(false);
    }

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.setNewEntry();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if ( !this.actualEntry.hasTranslation(this.tfTranslation.getText()) ) {

            this.lblCorrectTranslation.setVisible(true);
            this.lblCorrectTranslation.setText( this.actualEntry.getTranslation() );
            this.pack();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	    this.bExit = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMain().setVisible(true);
            }
        });
    }*/

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnNext;
        private javax.swing.JButton btnOk;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel lblCorrectTranslation;
        private javax.swing.JLabel lblWord;
        private javax.swing.JTextField tfTranslation;
        // End of variables declaration//GEN-END:variables

}
